### ISSUE TITLE
Some random questions and feedback

### ISSUE THREAD

**Issue by internettrans** [framejs/framejs#6]
Hey Emil,

I saw [your post](https://medium.com/@emilrmoeller/i-feel-you-9ca8ba2c2608) on [my medium article](https://medium.com/canopy-tax/one-companys-relationship-with-custom-elements-d360baf3b253) a while ago but didn't get around to responding until now.

I just read over your documentation for framejs, and I like it! FrameJS definitely seems like a pretty lightweight abstraction on top of custom elements. Here were some of my thoughts and questions:

**Smaller, more specific thoughts**
- In your [event emitter docs](https://github.com/framejs/framejs#event-property-eventemitter), is what is emitted a CustomEvent whose `detail` property is whatever you pass to emit? In other words, is `this.isReady.emit('something')` the same thing as `customDomEl.dispatchEvent(new CustomEvent({detail: 'something'}))`?
- Are all functions on a class always called with the instance of the class as its context? For example, in [this example](https://github.com/framejs/framejs#listenevent-string-target-window--document-function) is the `clickedOnInstanceHandler` always called with the correct context? Or do users need to do `clickedOnInstanceHandler = () => {}` instead of `clickedOnInstanceHandler() {}`
- In your [property decorator example](https://github.com/framejs/framejs#property-property-any), where does the `data` variable come from? Is that a typo for `this.data`?
- Customized builtins. Are they supported?
- I'm glad that `this._renderOnPropertyChange ` is on by default for the lit-html and preact renderers. I wonder if it should just always be turned on? That might cause performance problems in some situations, see my comment in the below section about debouncing/batching.

**Broader, high level feedback**
- One of my first questions when reading about framejs renderers was if renders are debounced/batched. One problem we ran into at Canopy was that frameworks like React will setAttribute or set property values many times right in a row whenever a component re-renders. Usually frameworks are not conservative about doing things like `el.propertyName = value` and will do so even if the value hasn't changed. And they will do it for all properties and attributes right in a row. If you have 5-10 attributes/properties per custom element, with 5-10 instances of a custom element all being re-rendered by React (or any other framework) multiple times within a 100ms window, you might run into performance problems.
- One of the main challenges I've come across when implementing custom elements is the question "What should I do with my children DOM nodes that I didn't create?" Should the custom element overwrite the children DOM nodes? Or maybe the custom element just uses shadow dom and leaves the normal dom for whoever created the custom element? What if you want to process or manipulate the children DOM nodes?  I believe the [slot element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot) is intended to try to solve some of these problems, but it definitely doesn't solve all of them. Does FrameJS try to solve that problem at all? From the documentation, I'm not even sure if FrameJS defaults to shadow dom or not for its renderers (although [this header text seems to indicate it maybe _does_ default to shadow dom?](https://github.com/framejs/framejs#customelementtag-string-style-string-shadow-boolean--true-mode-open-closed)). If you could solve this particular problem in a good way, especially in a non-shadow-dom-y way, I think that that would be a compelling feature.
- You mentioned that SkateJS and other custom element frameworks don't work with typescript or with custom build setup. Could you elaborate? I have found skatejs to work pretty nicely with webpack, but are you using something else that doesn't allow you to install npm modules? And what about typescript was incompatible with SkateJS? Asking just out of curiosity.
- One of the biggest differences between a custom element and a framework component (like a React component), is "who creates and controls the dom element." With React components, the concept of a component and dom element are totally separate, which makes it clear who applies css classes, styles, etc to the dom element. Contrast that with a custom element. There is the "user" of the CE who does `document.createElement('x-foo')` and then there is the x-foo CE itself. Who should apply css to the `<x-foo class="" />`?? This is particularly relevant for customized builtin elements, since a `<button is="x-foo" />` may very well want to add css classes of its own to itself. But I think the question is still valid for autonomous custom elements -- should they be `display: inline` (which they are, by default), or should they be `display: block`? What if you want to add additional css styles to the element?? I think that is something that is not particularly clear with the CE specification and is left open to the implementor. I think it would be cool if FrameJS took a stance on that issue and then made it easy to do the right thing. For example, if the custom element is allowed to change its own css classes, it could be as simple as the browser builtin `this.classList.add('my-class')` and `this.classList.remove('my-class')`. However, how would that tie into the renderer concept? Does the renderer only apply to children of the CE? or does it apply to the CE itself??
- I think the biggest pro of what you've got here with FrameJS is the renderer concept. I think it is a big win because it is not clear when implementing a raw custom element how to best reflect updates in the properties/attributes to the dom. The way you're using decorators is also some decent syntactic sugar to help developers avoid learning about javascript property getters/setters, `static observedAttributes`, `CustomEvent`, etc, which probably lowers the barrier to entry for people less familiar with custom elements.

**Comment by internettrans** [comment]
Ha that might be a hot mess of random thoughts -- hopefully there's something useful buried in there :)

**Comment by emolr** [comment]
Hi @joeldenning !
Wow, thank you so much for your feedback and questions! I really really appreciate the time you have spend and commenting on the library!

It's a lot of questions, so i'm trying to answer them one by one, and please let me know if some of the answers are insufficient :)

Okay, here it goes:

#### Smaller, more specific thoughts

> In your event emitter docs, is what is emitted a CustomEvent whose detail property is whatever you pass to emit? In other words, is this.isReady.emit('something') the same thing as customDomEl.dispatchEvent(new CustomEvent({detail: 'something'}))?

Yes, it is using 
```
new CustomEvent({
	detail: // your-content from .emit(data),
	Bubbles: true
})
```

It's a helper to simplify event emitter creation :) 

> Are all functions on a class always called with the instance of the class as its context? For example, in this example is the clickedOnInstanceHandler always called with the correct context? Or do users need to do clickedOnInstanceHandler = () => {} instead of clickedOnInstanceHandler() {}

Yes, the `clickedOnInstanceHandler` is always called with the correct context. So `clickedOnInstanceHandler() {...}` is enough.

> In your property decorator example, where does the data variable come from? Is that a typo for this.data?

Whoops, thank you for spotting that, it was a typo, it should have been `this.data` and is now corrected in the readme.md

> Customized builtins. Are they supported?

I Am not sure what you mean by `Customized builtins` ? Can you elaborate?
But everything you would normally have available in TS/JS is available. The @CustomElement(...) decorator basically takes the defined class and modify it's prototype and returns it.

> I'm glad that this._renderOnPropertyChange is on by default for the lit-html and preact renderers. I wonder if it should just always be turned on? That might cause performance problems in some situations, see my comment in the below section about debouncing/batching.

The reason for it to be turned off by default is because the default renderer just writes the returned template from the `render() {}` function, and it may be fine for components that aren't using `<slot></slot>` and needs any rendering except initial rendering (like an  icon component, or layout components).

But if re-rendered for every propertyChange,  replacing the DOM will cause very unexpected side-effects for children thats Is slotted, and state management in the DOM can be hard.

#### Broader, high level feedback

> One of my first questions when reading about framejs renderers was if renders are debounced/batched. One problem we ran into at Canopy was that frameworks like React will setAttribute or set property values many times right in a row whenever a component re-renders. Usually frameworks are not conservative about doing things like el.propertyName = value and will do so even if the value hasn't changed. And they will do it for all properties and attributes right in a row. If you have 5-10 attributes/properties per custom element, with 5-10 instances of a custom element all being re-rendered by React (or any other framework) multiple times within a 100ms window, you might run into performance problems.

Thank you, this is such a great question. 
Actually I'm "batching" the changes by scheduling the render as a microtask in the `@CustomElement(...)` decorator https://github.com/framejs/framejs/blob/master/packages/core/src/decorators/custom-element.ts#L99

This means that it's waiting for a free "tick" before it's running the renderer. So if 5 properties changes at the same time, it only renders once, an then the performance can be optimised tremendously by using VDOM or LIT-HTML inside the custom element so it's only changing the parts og the template that are affected by the changed properties.

> One of the main challenges I've come across when implementing custom elements is the question "What should I do with my children DOM nodes that I didn't create?" Should the custom element overwrite the children DOM nodes? Or maybe the custom element just uses shadow dom and leaves the normal dom for whoever created the custom element? What if you want to process or manipulate the children DOM nodes? I believe the slot element is intended to try to solve some of these problems, but it definitely doesn't solve all of them. Does FrameJS try to solve that problem at all? From the documentation, I'm not even sure if FrameJS defaults to shadow dom or not for its renderers (although this header text seems to indicate it maybe does default to shadow dom?). If you could solve this particular problem in a good way, especially in a non-shadow-dom-y way, I think that that would be a compelling feature.

I don't think there is a single good answer to this question hehe. I really get what you are asking, and I have solved some parts by changing the architecture of some components, and I strive to always use the shadow-DOM as it gives a great separation from the light-dom.  A way I solved the issue in a `tabs` component was that a made a `custom element` for a tab, and one for a tab-group. Then every time a single tab is inserted into the DOM it emits an event which is an reference to itself.  Then then tab-group can listen for that event, and update labels (create/delete) from the instance of the tab instead of reading the light dom. This feels very natural. And this technique can be extended to `tab title change events` etc..

FrameJS uses shadowDOM by default, but has an option not to do so `@CustomElement({shadow: false})`, problem is that it will then "overwrite" the light-dom and you'd need to pass content through properties and attributes instead of the light-dom. (This Is what stencilJS is doing https://stenciljs.com/docs/my-first-component) but, I'd much rather use shadowDOM as it makes the components more versatile and useful without any JS pre-rendering. 

An example of "server side rendering" from a lets say, a php cms:

```html
<my component title="my title that every user will see">
	<h1>My title that no one but search engine crawlers will see</h1>
</my-component>
```

By using shadowDOM its possible to present semantic correct markup for programs, and visually pleasing for visitors. This is what EA games https://www.ea.com/da-dk are doing. (They are using polymer, saw a talk from them at polymer summit in Copenhagen, great talks btw ;) 

I'm not sure if those are the answers you where hoping for, and you have been through some cases I haven't yet ? 

> You mentioned that SkateJS and other custom element frameworks don't work with typescript or with custom build setup. Could you elaborate? I have found skatejs to work pretty nicely with webpack, but are you using something else that doesn't allow you to install npm modules? And what about typescript was incompatible with SkateJS? Asking just out of curiosity.

The reason I'm saying that skateJS isn't working with typescript is because it doesn't include type definitions... anymore, and the last time I looked at the issue on GitHub no one had picked up the task to port it to @types. When that happens, it will work fine with typescript again :) 
https://github.com/skatejs/skatejs/issues/1270

> One of the biggest differences between a custom element and a framework component (like a React component), is "who creates and controls the dom element." With React components, the concept of a component and dom element are totally separate, which makes it clear who applies css classes, styles, etc to the dom element. Contrast that with a custom element. There is the "user" of the CE who does document.createElement('x-foo') and then there is the x-foo CE itself. Who should apply css to the <x-foo class="" />?? This is particularly relevant for customized builtin elements, since a <button is="x-foo" /> may very well want to add css classes of its own to itself. But I think the question is still valid for autonomous custom elements -- should they be display: inline (which they are, by default), or should they be display: block? What if you want to add additional css styles to the element?? I think that is something that is not particularly clear with the CE specification and is left open to the implementor. I think it would be cool if FrameJS took a stance on that issue and then made it easy to do the right thing. For example, if the custom element is allowed to change its own css classes, it could be as simple as the browser builtin this.classList.add('my-class') and this.classList.remove('my-class'). However, how would that tie into the renderer concept? Does the renderer only apply to children of the CE? or does it apply to the CE itself??

Great question! 
It's correct that FrameJS don't help developers with these details that are pretty non-self-explanatory, but there is a couple of reasons for it actually.   Looking at this article https://developers.google.com/web/fundamentals/web-components/customelements#extendhtml it seems that it in the future looks like other elements that `HTMLElement` can be extended. So it would probably mean that extending `HTMLButtonElement` would make the custom element `display: inline-block` instead, or `HTMLDivElement` would make it `display: block`. 

I'm not sure what frameJS could do about the issue without creating unintended side effects, but I'd love to talk more about it! 

Have you had a shared css with default styling for components? Or how have you dealt with this ? 

I think I will make a reference to best practices from google about the matter of self-applying classes the the "host" element:
https://developers.google.com/web/fundamentals/web-components/best-practices

`Do not self-apply classes.`
Why?
Elements that need to express their state should do so using attributes. The class attribute is generally considered to be owned by the developer using your element, and writing to it yourself may inadvertently stomp on developer classes. |

> I think the biggest pro of what you've got here with FrameJS is the renderer concept. I think it is a big win because it is not clear when implementing a raw custom element how to best reflect updates in the properties/attributes to the dom. The way you're using decorators is also some decent syntactic sugar to help developers avoid learning about javascript property getters/setters, static observedAttributes, CustomEvent, etc, which probably lowers the barrier to entry for people less familiar with custom elements.

Thank you! It's really great to hear!

Actually the renderer concept is very much inspired by @skatejs and all credit for thinking out the architecture for that goes to them! 

I made the different decorators to make the components cleaner (like angular, stenciljs, react) but also to save kb by sharing the same logic between components, and to make the components less error prone by having the complex logic distributed from a source leaving only specific component logic for the developer to apply.

### Thank you so much @joeldenning !
I can't even express the joy from reading your feedback and comments, and the fact that you have taken the time to go through it with so much care.

**Comment by emolr** [comment]
I'm closing this. Feel free to reopen if youre feeling like continue this thread :)
